### ISSUE TITLE
DLE 10.6

### ISSUE THREAD

**Issue by nanodracula** [olegabr/dle2wordpress#1]
Здравствуйте!
работает ли данный скрипт под DLE 10.6?

**Comment by olegabr** [comment]
Привет!
Версия DLE, с которой я работал, у меня лежит файлом dle95.zip
подозреваю, что это 9.5

**Comment by olegabr** [comment]
В описание добавил параграф с версиями.

**Comment by nanodracula** [comment]
А не планируете его адаптировать под 10.4-10.6? Или сделать платную версию даже? Для многих людей это актуально судя по форумам, да и я бы баксов 50 не пожалел бы для этого)

**Comment by olegabr** [comment]
Платные сервисы уже существуют. У меня нет ресурсов с ними тягаться. Этот репозиторий просто чтобы код не потерялся, или если вдруг кому-то пользу принесёт. Адаптировать под свежие версии DLE и WP не так уж и сложно, надо немного в код вникнуть. pool-реквесты приветствуются :-)

**Comment by nanodracula** [comment]
Ну в cms2cms для моего сайта 510 баксов выдало) да и сервис какой то стремный у них, все cms почти конвертирует... Судя по отзывам постоянно у них проблемы какие то
Да я бы с удовольствием но с sql и php не особо есть время разбираться, но готов заплатить за качественную работу...

**Comment by olegabr** [comment]
сюда контакты скинь, обсудим: olegabr [собака] mail [] точка [] ру

**Comment by nanodracula** [comment]
окей, я думаю тогда уже после нг все обсудим, спасибо)
